### ISSUE TITLE
Instagram Plugin does not auto-update

### ISSUE THREAD

**Issue by Zchanson1** [Zchanson1/ImplantCompare#1]
The plugin for the instagram feed does not update automatically.

**Comment by Zchanson1** [comment]
Hey Phil - where are we at with this one?

**Comment by Zchanson1** [comment]
Is this one closed?

**Comment by phil-lgr** [comment]
Hi, it will not, I checked on how to update the embed and it`s not easy to automatically fetch the newest one this one will need to be estimated and priced since it`s not a trivial task..

**Comment by phil-lgr** [comment]
After discussion with Blake the other day: the social section was providing little to no interest, was more of a suggestion on my side, so we remove it. The embeds are super heavy... good thing we don't have them anymore.
