### ISSUE TITLE
Begin Android App

### ISSUE THREAD

**Issue by Zchanson1** [Zchanson1/ImplantCompare#2]
Begin coding for the Android App - Solely focusing on using the existing WebApp.

**Comment by phil-lgr** [comment]
My recommendation for android... don't go native, google is actively pushing for a faster web. 

Check out PWAs https://developers.google.com/web/progressive-web-apps/ it's nothing crazy, just webapps coded to work well on 3G connection, with caching, installable on the home screen etc.

Web apps on the Chrome browser on Android can be installed to screen, and they now support native WEB PUSH notification (this is what we use right now through OneSignal)

**Comment by phil-lgr** [comment]
Closing, will reopen issue if have something to discuss about android app specifics.
