### ISSUE TITLE
Integrate Livestream API 

### ISSUE THREAD

**Issue by blakeic** [Zchanson1/ImplantCompare#20]
We need to have a phone call very soon about this as we may be better off integrating this API before any additional changes.  This API will give us all of the abilities that users of livestream.com has by pulling from our database and allowing members to livestream at any time.  Would like to talk about restricting access etc.

**Comment by Zchanson1** [comment]
@phil-lgr Where are we after the convo with Livestream?

**Comment by phil-lgr** [comment]
Like we discussed, it`s possible to pull content out, but no way, right now, to upload live events/videos from our own apps.
